### PR TITLE
improve default settings for Colors

### PR DESCRIPTION
**Pull request by wolframhaussig**
I have fixed invisibility of `StylableTextBox` and `StylableComboBox`.

For `StylableComboBox`, I have overwritten `OnPaintBackground` to create a border only for `DropDownStyle` `Simple` and `DropDown` as the invisibility was not an issue for `DropDownList`, but I can remove this condition if we want to. @Nockiro what do you think?

### CODE REVIEW

**Comment by Nockiro** [comment]
I think, for the moment, we can leave the condition in.  
With this issue, I noticed that some of the default border colors we use don't match up, should we open a separate issue for this?

**Comment by Nockiro** [comment]
And another thing I noticed on the topic of improving default colors: The colors of `StylableListView` still have `Color.Orange` as default for both fore _and_ back color for selected items (I suspect because of my earlier tests), maybe we should fix this to be more near the original controls.

**Comment by wolframhaussig** [comment]
> And another thing I noticed on the topic of improving default colors: The colors of `StylableListView` still have `Color.Orange` as default for both fore _and_ back color for selected items

Hm, when are the colors used? I could not get the example form to show orange fields - `drawGroupHeader` was not even executed...

**Comment by Nockiro** [comment]
> > And another thing I noticed on the topic of improving default colors: The colors of `StylableListView` still have `Color.Orange` as default for both fore _and_ back color for selected items
> 
> Hm, when are the colors used? I could not get the example form to show orange fields - `drawGroupHeader` was not even executed...

This is mainly the case for ListViews with `View=Details` in my case - you can just try it with the current example project of this repo.

**Comment by wolframhaussig** [comment]
> With this issue, I noticed that some of the default border colors we use don't match up

As this issue is specifically for those mismatches I would be happy to fix them as part of this PR if you tell me which problems you found.

**Comment by wolframhaussig** [comment]
As this seems to involve a bigger discussion I opened #26

**Review by Nockiro — APPROVED** [review]

**Pull request merged**
